project:
  type: sdca-theme
  output-dir: "."

toc: true
website:
  title: "ZKA"
  navbar: 
    title: " "
    pinned: true
    tools:
      - icon: github
        href: https://github.com/steno-aarhus/
      - icon: envelope-arrow-up-fill
        href: mailto:contact@zheer.dk
    id: rcc
    style: "docked"
    left: 
      - text: "R Coding Caf√©"
        href: index.html
      - text: "Practical info"
        href: practical-info.html
      - text: "Notes"
        href: notes/lesson-notes/index.html
  sidebar:
      style: "docked"
      contents: 
        - section: "Lesson notes"
          contents: notes/lesson-notes/*
        - section: "Extra notes and tutorials"
          contents: notes/extra/*

format: sdca-theme-html