project:
  type: website
  output-dir: "."

website:
  title: "ZKA"
  navbar: 
    title: " "
    id: rcc
    style: "docked"
    background: "#990032"
    left: 
      - text: "R Coding Caf√©"
        href: index.html
      - text: "Practical info"
        href: practical-info.html
      - text: "Notes"
        href: notes.html
    right:
      - text: "{{< iconify fa6-solid at title='E-mail' width=19px >}} <span id='hide-nav-item'>E-mail</span>"
        href: mailto:contact@zheer.dk
      - text: "{{< iconify fa6-brands square-github title='GitHub' width=19px >}} <span id='hide-nav-item'>GitHub</span>"
        href: https://github.com/steno-aarhus
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true
    css: css/style.css