project:
  type: sdca-theme
  output-dir: "."

toc: true
website:
  title: "ZKA"
  navbar: 
    title: " "
    pinned: true
    tools:
      - icon: github
        href: https://github.com/steno-aarhus/
      - icon: envelope-arrow-up-fill
        href: mailto:contact@zheer.dk
    id: rcc
    style: "docked"
    background: "#990032"
    left: 
      - text: "R Coding Caf√©"
        href: index.html
      - text: "Practical info"
        href: practical-info.html
      - text: "Notes"
        href: notes.html

format: 
  sdca-theme-html:
    toc: true